name: Build and Test

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
  push:
    branches-ignore:
      # When you enable the release workflow, change the line below to your main branch
      # to avoid the duplicate action worktime.
      - change-this-to-default-branch-when-the-release-workflow-enabled

jobs:
  build-test:
    name: Build, Lint and Test
    uses: tksst/github-actions-workflows/.github/workflows/nodejs-pnpm.yml@118c76c1845aa9c8974dd0664742f4c46ed25304
    permissions:
      actions: write
      contents: read
