name: Build and Test

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
  push:
    # branches:
    # branches-ignore:
    #  - master
    #  - alpha

jobs:
  build-test:
    name: Build, Lint and Test
    uses: tksst/github-actions-workflows/.github/workflows/nodejs-pnpm.yml@14553fc8b894ed94edaea724ca6b11f13312e850
